# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-31 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Punto_de_venta', '0002_auto_20191025_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='caja',
        ),
        migrations.AddField(
            model_name='ventas',
            name='caja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Caja'),
            preserve_default=False,
        ),
    ]
