# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-12 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Punto_de_venta', '0004_auto_20191031_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
