# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Punto_de_venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='caja_operacion',
            new_name='CajaOperacion',
        ),
        migrations.RenameModel(
            old_name='dpto',
            new_name='Departamento',
        ),
        migrations.RenameModel(
            old_name='detalle_venta',
            new_name='DetalleVenta',
        ),
        migrations.RenameModel(
            old_name='unidad_medida',
            new_name='UnidadMedida',
        ),
        migrations.AlterField(
            model_name='cajaoperacion',
            name='cajas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Caja'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Contacto'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Productos'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='ventas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Ventas'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Marca'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='provedores',
            field=models.ManyToManyField(to='Punto_de_venta.Provedores'),
        ),
        migrations.AlterField(
            model_name='provedores',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Contacto'),
        ),
        migrations.AlterField(
            model_name='provedores',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='caja',
            field=models.ManyToManyField(to='Punto_de_venta.Caja'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Punto_de_venta.Clientes'),
        ),
    ]
